apiVersion: v1
appVersion: 1.0.0
version: 1.0.0
name: starship-webhook
description: starship-webhook
icon: https://davidlovezoe.files.wordpress.com/2019/08/spring-cloud.jpg
maintainers:
- email: huxz01@mingyuanyun.com
  name: huxz
sources:
  - https://starship-pass.github.io/starship/starship-webhook
