apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-cert-setup
  namespace: starship-mutating-webhook
spec:
  template:
    spec:
      imagePullSecrets:
        - name: webhook-cert-secret
      serviceAccountName: webhook-cert-sa
      containers:
      - name: webhook-cert-setup
        # This is a minimal kubectl image based on Alpine Linux that signs certificates using the k8s extension api server
        image: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com/cloudnative/k8s-webhook-cert-manager:202107141209
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "starship-webhook-service"
          - "--webhook"
          - "mutating-webhook.starship.com"
          - "--secret"
          - "starship-mutating-tls-secret"
          - "--namespace"
          - "starship-mutating-webhook"
      restartPolicy: OnFailure
  backoffLimit: 3