apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook.starship.com
  namespace: starship-mutating-webhook
webhooks:
  - name: mutating-webhook.starship.com
    objectSelector:
      matchLabels:
        registry: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com
    rules:
      - apiGroups:   ["apps"]
        apiVersions: ["v1"]
        operations:  ["CREATE","UPDATE"]
        resources:   ["deployments","statefulsets","daemonsets"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: starship-mutating-webhook
        name: starship-webhook-service
        path: /mutate
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10

#apiVersion: admissionregistration.k8s.io/v1
#kind: MutatingWebhookConfiguration
#metadata:
#  name: mutating-webhook.starship.com
#  namespace: starship-mutating-webhook
#webhooks:
#  - name: mutating-webhook.starship.com
#    namespaceSelector:
#      matchLabels:
#        registry: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com
##    objectSelector:
##      matchLabels:
##        registry: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com
#    rules:
#      - apiGroups:   ["apps"]
#        apiVersions: ["v1"]
#        operations:  ["CREATE","UPDATE"]
#        resources:   ["deployments","statefulset"]
#        scope:       "Namespaced"
#    clientConfig:
#      service:
#        namespace: starship-mutating-webhook
#        name: starship-webhook-service
#        path: /mutate
#    admissionReviewVersions: ["v1", "v1beta1"]
#    sideEffects: None
#    timeoutSeconds: 10